cache:
  pipeline: [~/.npm, ~/.gradle]

shared:
  image: maven:3.6.3-jdk-8
  annotations:
    screwdriver.cd/ram: TURBO
    screwdriver.cd/cpu: TURBO
    steps:
      - .: &install-node
          install-node: |
            sd-cmd exec screwdriver/install-nodejs@latest $NODE_VERSION
            export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" && nvm use node
      - .: &npm-cache-verify
          npm-cache-verify: npm cache verify
      - .: &npm-ci
          npm-ci: npm ci --unsafe-perm
      - .: &install-chrome
          install-chrome: ./build-scripts/setup-chrome.sh
    jobs:
      main-npm-test-job: &main-npm-test-job
        steps:
          - *install-node
          - *npm-cache-verify
          - *npm-ci
          - *install-chrome
          - test-package: npx lerna run test --scope $PACKAGE --stream;
        requires:
          - ~pr
          - ~commit
  environment:
    NODE_VERSION: 14.16.1
    JOBS: 4

jobs:
  lint:
    <<: *main-npm-test-job
    steps:
      - *install-node
      - *npm-ci
      # TODO add lint meta https://docs.screwdriver.cd/user-guide/metadata#additional-pull-request-checks
      - lint-pretty: npx prettier -c --config prettier.config.js packages/*/{addon,tests}/**/*.{js,ts};
      - lint-styles: npx stylelint "**/*.scss";
      - lint-addons: npx lerna run lint --stream;
  main-admin:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-admin
  main-app:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-app
  main-core:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-core
  main-dashboards:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-dashboards
  main-data:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-data
  main-directory:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-directory
  main-notifications:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-notifications
  main-reports:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-reports
  main-search:
    <<: *main-npm-test-job
    environment:
      PACKAGE: navi-search
  main-webservice:
    steps:
      - *install-node
      - *npm-ci
      - test-navi-webservice: cd packages/webservice && ./gradlew check && cd -;
    requires:
      - ~pr
      - ~commit
  main:
    annotations:
      screwdriver.cd/ram: MICRO
      screwdriver.cd/cpu: MICRO
    steps:
      - echo "success"
    requires:
      [
        lint,
        main-admin,
        main-app,
        main-core,
        main-dashboards,
        main-data,
        main-directory,
        main-notifications,
        main-reports,
        main-search,
        main-webservice,
      ]

  alpha-main:
    steps:
      - *install-node
      - *npm-ci
      - *install-chrome
      - test-navi-admin: npx lerna run test --scope navi-admin --stream;
      - test-navi-app: npx lerna run test --scope navi-app --stream;
      - test-navi-core: npx lerna run test --scope navi-core --stream;
      - test-navi-dashboards: npx lerna run test --scope navi-dashboards --stream;
      - test-navi-data: npx lerna run test --scope navi-data --stream;
      - test-navi-directory: npx lerna run test --scope navi-directory --stream;
      - test-navi-notifications: npx lerna run test --scope navi-notifications --stream;
      - test-navi-reports: npx lerna run test --scope navi-reports --stream;
      - test-navi-search: npx lerna run test --scope navi-search --stream;
      - test-navi-webservice: cd packages/webservice && ./gradlew check && cd -;
    requires:
      - ~commit:0.2.x-alpha
      - ~pr:0.2.x-alpha

  publish-npm:
    requires:
      - ~main
      - ~alpha-main
    environment:
      GIT_SHALLOW_CLONE: false
    steps:
      - *install-node
      - *npm-ci
      - publish: ./scripts/npm-publish.sh
    secrets:
      - NPM_TOKEN

  publish-maven:
    annotations:
      screwdriver.cd/ram: LOW
      screwdriver.cd/cpu: LOW
    requires:
      - ~main
      - ~alpha-main
    steps:
      - decrypt: ./scripts/decrypt.sh
      - publish: ./scripts/maven-publish.sh
    secrets:
      - GPG_KEY
      - GPG_ENCPHRASE
      - OSSRH_TOKEN
      - OSSRH_USER
      - GPG_PASSPHRASE

  gh-pages:
    requires: main
    environment:
      BUILD_NAVI_DEMO: true
    steps:
      - *install-node
      - *npm-ci
      - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git /tmp/ci
      - build-pages: |
          cd packages/app
          npx ember github-pages:commit --message "Deploy gh-pages from $SD_BUILD_SHA" --destination ../../
      - deploy: |
          . /tmp/ci/git-ssh.sh
          git push origin gh-pages:gh-pages
    secrets:
      - GIT_KEY_BASE64
