export default [
  {
    id: '-1',
    description: 'NULL',
    planRate: '',
    decimalUnits: '0',
  },
  {
    id: '-2',
    description: 'UNKNOWN',
    planRate: '',
    decimalUnits: '0',
  },
  {
    id: 'AED',
    description: 'Dirhams',
    planRate: '3.6729',
    decimalUnits: '2',
  },
  {
    id: 'AFA',
    description: 'Afghanis',
    planRate: '',
    decimalUnits: '0',
  },
  {
    id: 'ALL',
    description: 'Leke',
    planRate: '',
    decimalUnits: '2',
  },
  {
    id: 'AMD',
    description: 'Drams',
    planRate: '',
    decimalUnits: '2',
  },
  {
    id: 'ANG',
    description: 'Guilders',
    planRate: '',
    decimalUnits: '2',
  },
  {
    id: 'AOA',
    description: 'Kwanza',
    planRate: '',
    decimalUnits: '2',
  },
  {
    id: 'ARS',
    description: 'Pesos',
    planRate: '15.2109',
    decimalUnits: '2',
  },
  {
    id: 'AUD',
    description: 'Dollars',
    planRate: '1.31613583',
    decimalUnits: '2',
  },
  {
    id: 'CAD',
    description: 'Dollars',
    planRate: '1.3386',
    decimalUnits: '2',
  },
  {
    id: 'USD',
    description: 'Dollars',
    planRate: '1.0',
    decimalUnits: '2',
  },
  {
    id: 'EUR',
    description: 'Euro',
    planRate: '0.9154994',
    decimalUnits: '2',
  },
  {
    id: 'INR',
    description: 'Rupees',
    planRate: '66.86651',
    decimalUnits: '2',
  },
];
